### ISSUE TITLE
三星设备与dialog重合

### ISSUE THREAD

**Issue by whsgzcy** [swustmuzi/SoftKeyboardTopTool#1]
其中在部分设备 虚拟键高度没有算进去 会导致 dialog 与 软盘重合

加入以下判断即可

/**
     * 判断是否有虚拟按键
     *
     * @return
     */
    public static boolean checkDeviceHasNavigationBar() {
        boolean hasNavigationBar = false;
        Resources rs = Utils.getContext().getResources();
        int id = rs.getIdentifier("config_showNavigationBar", "bool", "android");
        if (id > 0) {
            hasNavigationBar = rs.getBoolean(id);
        }
        try {
            Class systemPropertiesClass = Class.forName("android.os.SystemProperties");
            Method m = systemPropertiesClass.getMethod("get", String.class);
            String navBarOverride = (String) m.invoke(systemPropertiesClass, "qemu.hw.mainkeys");
            if ("1".equals(navBarOverride)) {
                hasNavigationBar = false;
            } else if ("0".equals(navBarOverride)) {
                hasNavigationBar = true;
            }
        } catch (Exception e) {
            return false;
        }
        return hasNavigationBar;
    }

    /**
     * 获取虚拟按键 高度
     *
     * screen 获取软盘高度 没有将此高度加入
     * @param activity
     * @return
     */
    public static int getNavigationBarHeight(Context activity) {
        Resources resources = activity.getResources();
        int resourceId = resources.getIdentifier("navigation_bar_height",
                "dimen", "android");
        //获取NavigationBar的高度
        int height = resources.getDimensionPixelSize(resourceId);
        return height;
    }

**Comment by swustmuzi** [comment]
> 其中在部分设备 虚拟键高度没有算进去 会导致 dialog 与 软盘重合
> 
> 加入以下判断即可
> 
> /**
> * 判断是否有虚拟按键
> *
> * @return
> */
> public static boolean checkDeviceHasNavigationBar() {
> boolean hasNavigationBar = false;
> Resources rs = Utils.getContext().getResources();
> int id = rs.getIdentifier("config_showNavigationBar", "bool", "android");
> if (id > 0) {
> hasNavigationBar = rs.getBoolean(id);
> }
> try {
> Class systemPropertiesClass = Class.forName("android.os.SystemProperties");
> Method m = systemPropertiesClass.getMethod("get", String.class);
> String navBarOverride = (String) m.invoke(systemPropertiesClass, "qemu.hw.mainkeys");
> if ("1".equals(navBarOverride)) {
> hasNavigationBar = false;
> } else if ("0".equals(navBarOverride)) {
> hasNavigationBar = true;
> }
> } catch (Exception e) {
> return false;
> }
> return hasNavigationBar;
> }
> 
> ```
> /**
>  * 获取虚拟按键 高度
>  *
>  * screen 获取软盘高度 没有将此高度加入
>  * @param activity
>  * @return
>  */
> public static int getNavigationBarHeight(Context activity) {
>     Resources resources = activity.getResources();
>     int resourceId = resources.getIdentifier("navigation_bar_height",
>             "dimen", "android");
>     //获取NavigationBar的高度
>     int height = resources.getDimensionPixelSize(resourceId);
>     return height;
> }

**Comment by swustmuzi** [comment]
> 其中在部分设备 虚拟键高度没有算进去 会导致 dialog 与 软盘重合
> 
> 加入以下判断即可
> 
> /**
> * 判断是否有虚拟按键
> *
> * @return
> */
> public static boolean checkDeviceHasNavigationBar() {
> boolean hasNavigationBar = false;
> Resources rs = Utils.getContext().getResources();
> int id = rs.getIdentifier("config_showNavigationBar", "bool", "android");
> if (id > 0) {
> hasNavigationBar = rs.getBoolean(id);
> }
> try {
> Class systemPropertiesClass = Class.forName("android.os.SystemProperties");
> Method m = systemPropertiesClass.getMethod("get", String.class);
> String navBarOverride = (String) m.invoke(systemPropertiesClass, "qemu.hw.mainkeys");
> if ("1".equals(navBarOverride)) {
> hasNavigationBar = false;
> } else if ("0".equals(navBarOverride)) {
> hasNavigationBar = true;
> }
> } catch (Exception e) {
> return false;
> }
> return hasNavigationBar;
> }
> 
> ```
> /**
>  * 获取虚拟按键 高度
>  *
>  * screen 获取软盘高度 没有将此高度加入
>  * @param activity
>  * @return
>  */
> public static int getNavigationBarHeight(Context activity) {
>     Resources resources = activity.getResources();
>     int resourceId = resources.getIdentifier("navigation_bar_height",
>             "dimen", "android");
>     //获取NavigationBar的高度
>     int height = resources.getDimensionPixelSize(resourceId);
>     return height;
> }
> ```

是的，需要考虑虚拟按键，把这个高度算上就行了
